name: not_potato
description: A simple Flutter application to determine whether or not an image contains a potato.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^0.4.0+9
  firebase_ml_vision: ^0.9.4
  camera: ^0.5.8+2
  path_provider: ^1.6.11

flutter:
  uses-material-design: true
  assets:
    - assets/potatoes/